"use client"

import { useEffect, useMemo, useRef, useState } from "react"
import { toJpeg } from "html-to-image"
import { listInvoices, saveInvoice, type InvoicePayload } from "./actions/invoices"

type HistoryRow = Awaited<ReturnType<typeof listInvoices>>[number]
const BASE_TOTAL = 1850
const defaults: InvoicePayload = { billTo: "NEXA FREIGHT LLC\n1450 NW 87th Avenue\nMiami, FL 33172", securityFee: "31.00", deliveryFee: "5.00", invoiceDate: "2026-05-18", time: "10:30", dueDate: "2026-05-21", invoiceNumber: "AWB18534781" }
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" })
const amount = (v: string) => Math.max(0, Number.parseFloat(v) || 0)
const date = (v: string) => v ? new Intl.DateTimeFormat("en-US", { month: "short", day: "2-digit", year: "numeric" }).format(new Date(`${v}T12:00:00`)) : "—"

function ShipMark({ small = false }: { small?: boolean }) { return <div className={`ship-mark ${small ? "ship-mark-small" : ""}`} aria-label="UNIFET Shipping logo"><span>UNIFET</span><b>✧</b><small>SHIPPING</small></div> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}</label> }

function Invoice({ data, exportRef }: { data: InvoicePayload; exportRef: React.RefObject<HTMLElement | null> }) {
  const security = amount(data.securityFee), delivery = amount(data.deliveryFee), total = BASE_TOTAL + security + delivery
  const rows = [["AWB", 1250, "Miami — Port handling and freight service"], ["Price", 600, "Bulk Tank cargo transport"], ["Storage", 0, "Storage and documentation"], ["Destination", 0, "Saudi Arabia"], ["Fee", security, "Security fee"], ["Delivery", delivery, "Delivery fee"]] as const
  return <article ref={exportRef} className="invoice-paper"><header className="invoice-head"><div className="brand"><ShipMark /><div><strong>UNIFET</strong><b>SHIPPING COMPANY</b><small>Reliable global freight solutions</small></div></div><div className="bill"><label>BILL TO</label><strong>{data.billTo || "No recipient entered"}</strong><div className="meta"><span>Invoice #</span><b>{data.invoiceNumber || "—"}</b><span>Created</span><b>{date(data.invoiceDate)}</b><span>Due Date</span><b>{date(data.dueDate)}</b><span>Time</span><b>{data.time || "—"}</b></div></div></header><table className="invoice-table"><thead><tr><th>Invoice date</th><th>Meta</th><th>Payment</th><th>Total</th><th>Description</th></tr></thead><tbody>{rows.map(([name, value, description]) => <tr key={name}><td>{date(data.invoiceDate)}</td><td>{name}</td><td className="right">{value ? money.format(value) : "—"}</td><td className="right">{value ? money.format(value) : "—"}</td><td>{description}</td></tr>)}</tbody></table><footer className="invoice-foot"><div><span>Thank you for choosing UNIFET Shipping.</span><small>Questions? Contact our operations team for assistance.</small></div><div className="total"><span>Grand total</span><strong>{money.format(total)}</strong><small>USD · Due {date(data.dueDate)}</small></div></footer></article>
}

export default function Home() {
  const [form, setForm] = useState(defaults), [invoice, setInvoice] = useState(defaults), [history, setHistory] = useState<HistoryRow[]>([]), [status, setStatus] = useState("Ready to generate"), [busy, setBusy] = useState(false)
  const exportRef = useRef<HTMLElement | null>(null)
  const total = useMemo(() => BASE_TOTAL + amount(form.securityFee) + amount(form.deliveryFee), [form.securityFee, form.deliveryFee])
  useEffect(() => { listInvoices().then(setHistory).catch(() => setStatus("History unavailable")) }, [])
  const update = (key: keyof InvoicePayload, value: string) => setForm((current) => ({ ...current, [key]: value }))
  async function generate() { setInvoice(form); setBusy(true); setStatus("Saving to history…"); try { const row = await saveInvoice(form); setHistory((items) => [{ ...row, invoiceData: form, securityFee: Number(row.securityFee), deliveryFee: Number(row.deliveryFee), total: Number(row.total) } as HistoryRow, ...items.filter((item) => item.id !== row.id)].slice(0, 8)); setStatus("Invoice saved · ready to download") } catch { setStatus("Preview ready · history unavailable") } finally { setBusy(false) } }
  async function download() { if (!exportRef.current) return; setBusy(true); setStatus("Rendering 1500 × 1047 JPEG…"); try { const dataUrl = await toJpeg(exportRef.current, { quality: 0.96, pixelRatio: 1, width: 1500, height: 1047, backgroundColor: "#ffffff", style: { width: "1500px", height: "1047px" } }); const link = document.createElement("a"); link.download = `${invoice.invoiceNumber || "unifet-invoice"}.jpg`; link.href = dataUrl; link.click(); setStatus("JPEG downloaded") } catch { setStatus("Could not render JPEG") } finally { setBusy(false) } }
  return <main className="app-shell"><header className="topbar"><div className="top-brand"><ShipMark small /><div><strong>UNIFET / OPERATIONS</strong><span>Shipping invoice studio</span></div></div><div className="top-total"><span>Live total</span><strong>{money.format(total)}</strong></div></header><section className="workspace"><aside className="editor-panel"><div className="section-heading"><div><span className="eyebrow">01 · Invoice details</span><h1>Generate an invoice</h1></div><span className="status-dot" aria-label={status} /></div><div className="form-grid"><Field label="Bill To"><textarea value={form.billTo} onChange={(e) => update("billTo", e.target.value)} rows={3} /></Field><div className="field-row"><Field label="Invoice date"><input type="date" value={form.invoiceDate} onChange={(e) => update("invoiceDate", e.target.value)} /></Field><Field label="Time"><input type="time" value={form.time} onChange={(e) => update("time", e.target.value)} /></Field></div><div className="field-row"><Field label="Due date"><input type="date" value={form.dueDate} onChange={(e) => update("dueDate", e.target.value)} /></Field><Field label="Invoice #"><input value={form.invoiceNumber} onChange={(e) => update("invoiceNumber", e.target.value)} /></Field></div><div className="field-row fees"><Field label="Security fee"><input type="number" min="0" step="0.01" value={form.securityFee} onChange={(e) => update("securityFee", e.target.value)} /></Field><Field label="Delivery fee"><input type="number" min="0" step="0.01" value={form.deliveryFee} onChange={(e) => update("deliveryFee", e.target.value)} /></Field></div></div><div className="actions"><button className="button primary" onClick={generate} disabled={busy}>Generate & save</button><button className="button" onClick={download} disabled={busy}>Download JPEG</button><button className="reset" onClick={() => { setForm(defaults); setInvoice(defaults); setStatus("Form reset") }}>Reset</button></div><div className="history"><div className="section-heading compact"><span className="eyebrow">02 · Recent history</span><span>{history.length} saved</span></div>{history.length ? history.slice(0, 4).map((item) => <button className="history-item" key={item.id} onClick={() => { setForm(item.invoiceData); setInvoice(item.invoiceData); setStatus("Restored from history") }}><span><b>{item.invoiceNumber}</b><small>{date(item.invoiceDate)} · {item.billTo.split("\n")[0]}</small></span><strong>{money.format(item.total)}</strong></button>) : <p className="empty">Generated invoices will appear here.</p>}</div></aside><section className="preview-panel"><div className="preview-label"><span><i /> Live invoice preview</span><small>{status}</small></div><div className="preview-frame"><Invoice data={invoice} exportRef={exportRef} /></div></section></section></main>
}
